### ISSUE TITLE
Palette Swapping

### ISSUE THREAD

**Issue by Alevam-Inc** [KoBeWi/Godot-Gradient-Shift-Shader#1]
I think that this is a great shader, but it would be nice if there was a way to quickly swap between pallets to create a strobing or pulsing effect.

**Comment by KoBeWi** [comment]
Can you show a GIF of how it would look like?

**Comment by Alevam-Inc** [comment]
Sure.
![Pulse](https://user-images.githubusercontent.com/50853470/141480622-c4a24e6f-00a1-47e4-b5b2-bcf14901f5e7.gif)

**Comment by Alevam-Inc** [comment]
Something like this:
![Pulse](https://user-images.githubusercontent.com/50853470/141600079-dbeeafa8-fa47-496b-bfce-871d0fcc4cff.gif)

**Comment by KoBeWi** [comment]
Looks doable with a texture array.

**Comment by Alevam-Inc** [comment]
How would I go about coding that for a shader?

**Comment by Alevam-Inc** [comment]
How would one go about adapting the shader to use a texture array then?

**Comment by Alevam-Inc** [comment]
I would Also settle for this:
![Pulse2](https://user-images.githubusercontent.com/50853470/141650547-75a3b1af-8cc0-491b-b5f2-0cde450b6ff6.gif)

**Comment by Alevam-Inc** [comment]
Would a texture atlas work as well?

**Comment by KoBeWi** [comment]
I finally had time to give this a proper check.

My original shader is about palette cycling, i.e. you have one palette and just cycle the color indices.
What you request is palette swapping, which is something different. Cycling is more performant, because it doesn't involve color comparison.

That said, I made a relatively simple swapping shader based on your request:
[Swapping.zip](https://github.com/KoBeWi/Godot-Gradient-Shift-Shader/files/7532576/Swapping.zip)
You just need to provide a palette and FPS and it will use the first row of palette as reference and automatically animate the sprite. It's more expensive than my original shader, but I tried to optimize it so it's not bad.

**Comment by Alevam-Inc** [comment]
I tried it out but it doesn't seem to be working.

**Comment by Alevam-Inc** [comment]
I just tried it out and it works!

**Comment by Alevam-Inc** [comment]
I just tried it out and the only nitpick I really have is that I would prefer to be able to map the palettes to a completely monochrome (black and white) image, but overall it's very good, thank you.

**Comment by Alevam-Inc** [comment]
This is more like what I had in mind:
![Pulse](https://user-images.githubusercontent.com/50853470/141666962-fbdcc20d-3463-44a0-96a7-1edc7be3b613.gif)

**Comment by KoBeWi** [comment]
Here's updated shader:
[PaletteSwap.shader.txt](https://github.com/KoBeWi/Godot-Gradient-Shift-Shader/files/7534018/PaletteSwap.shader.txt)
I added a `skip_first_row` property. If you enable it, the first row will only be used as reference and excluded from animation. This way you can just put grayscale on top. Also if you use the skip with only 2 rows, you get a regular non-animated palette swap.

I might make a new asset out of this 🤔
There are a few palette swaps in the lib, but not sure if any of them supports animation.

**Comment by Alevam-Inc** [comment]
Thanks, you certainly have talent.

**Comment by Alevam-Inc** [comment]
Okay, just one last issue; When I apply use this to multiple sprites individually I can't use a different palette for each sprite.

**Comment by Alevam-Inc** [comment]
It doesn't seem to work with tile-mapped backgrounds.

**Comment by Alevam-Inc** [comment]
If I could just ask for one last feature; Would it be possible to make the shader turn a specific color completely transparent? Sort of like a chroma key?

**Comment by KoBeWi** [comment]
Change 
`COLOR = vec4(texture(palette, uv).rgb, color.a);`
to
`COLOR = texture(palette, uv);`
and it will use the alpha from the palette.

**Comment by Alevam-Inc** [comment]
It's perfect.

**Comment by Alevam-Inc** [comment]
Any plans for releasing this as a new asset? I know I am not the only one who has been looking for something like this.

**Comment by KoBeWi** [comment]
I submitted the asset, it will appear under this link when approved: https://godotengine.org/asset-library/asset/4715
And here's the repo: https://github.com/KoBeWi/Godot-Palette-Swap-Shader
The shader is the same, except I added an option to use the alpha values or not. I might later also add a simple script that will generate palettes from PNGs.

In any case, this can be now closed.
